### ISSUE TITLE
Build errors on macOS

### ISSUE THREAD

**Issue by v-ji** [LeeXun/word2vector#10]
Hi! First of all, thank you for this package. It's really difficult to find a well-working node module for word2vec.

While everything works fine on my Linux server, installation fails on macOS 10.14.5.

Below is part of the output with most of the errors omitted. Here's the [full output](https://github.com/LeeXun/word2vector/files/3376729/full-output.txt).

```
❯ npm i word2vector

> word2vector@2.1.0 install /Users/username/Downloads/w/node_modules/word2vector
> node-gyp rebuild

  CXX(target) Release/obj.target/w2vLeeXun/src/w2vLeeXun.o
../src/w2vLeeXun.cc:211:5: error: use of undeclared identifier 'Handle'
    Handle<Object> word_obj = New<Object>();
    ^
../src/w2vLeeXun.cc:211:12: error: 'Object' does not refer to a value
    Handle<Object> word_obj = New<Object>();
           ^
/Users/username/.node-gyp/12.5.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/w2vLeeXun.cc:211:20: error: use of undeclared identifier 'word_obj'
    Handle<Object> word_obj = New<Object>();
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [Release/obj.target/w2vLeeXun/src/w2vLeeXun.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/Downloads/w/node_modules/word2vector
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/username/Downloads/w/package.json'
npm WARN w No description
npm WARN w No repository field.
npm WARN w No README data
npm WARN w No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! word2vector@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the word2vector@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by LeeXun** [comment]
@vaviary glad it helped. Seems that v8 API had some critical updates to cause this issue. I will take a look at how to fix these problems when I am available. Downgrade to older nodejs version may fix it temporarily. Thanks for reporting.

**Comment by v-ji** [comment]
Hi, thanks for your reply! I've tried using the current Node.js LTS version (10.16.0) and it works flawlessly – I'll use that for now.
